version: '3'

services:
    php:
        container_name: ${COMPOSE_PROJECT_NAME}-php
        build:
            context: php
        volumes:
            - ${APP_PATH}:/var/${COMPOSE_PROJECT_NAME}
        environment:
            PHP_IDE_CONFIG: serverName=PHPSTORM
            AWS_ENDPOINT_URL: ${AWS_ENDOPOINT_URL}
            AWS_REGION: ${AWS_REGION}
            AWS_DEFAULT_REGION: ${AWS_REGION}
            DEFAULT_REGION: ${AW_REGION}
            AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY}
            AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}

    localstack:
        container_name: ${COMPOSE_PROJECT_NAME}-localstack
        image: localstack/localstack
        restart: always
        ports:
            - 4566:4566
            - 4571:4571
        environment:
            AWS_DEFAULT_REGION: ${REGION}
            AWS_REGION: ${REGION}
            DEFAULT_REGION: ${REGION}
            AWS_ACCESS_KEY_ID: ${ACCESS_KEY}
            AWS_SECRET_ACCESS_KEY: ${SECRET_ACCESS_KEY}
            SERVICES: secretsmanager,ssm
