name: CI

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['*']
    schedule:
        -   cron: '10 8 * * *'

jobs:
    tests:
        name: Tests - PHP ${{ matrix.php }}
        runs-on: ubuntu-latest
        timeout-minutes: 15
        strategy:
            matrix:
                php: [ '8.0', '8.1', '8.2', '8.3' ]
        steps:
            - uses: actions/checkout@v3

            - name: Run docker compose services
              run: |
                  cd docker
                  export PHP_VERSION=${{matrix.php}}
                  docker compose up -d

            - name: Install dependencies
              run: |
                  cd docker
                  docker compose -f docker-compose.yml exec -T php sh -c 'composer install'

            - name: Lint and test
              run: |
                  cd docker
                  docker compose -f docker-compose.yml exec -T php sh -c './scripts/quality.sh'
